### ISSUE TITLE
Restful service compilation failures

### ISSUE THREAD

**Issue by dushansachinda** [ballerina-guides/restful-service#17]
Dushans-MacBook-Pro-3:src dushan$ ballerina version
Ballerina 0.964.0
Dushans-MacBook-Pro-3:src dushan$ ballerina build restful_service
error: restful_service/order_mgt_service.bal:29:1: extraneous input 'endpoint'
error: restful_service/order_mgt_service.bal:29:40: mismatched input '{'. expecting ';'
error: restful_service/order_mgt_service.bal:30:9: mismatched input ':'. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:39:13: mismatched input ':'. expecting '>'
error: restful_service/order_mgt_service.bal:39:21: extraneous input '>'
error: restful_service/order_mgt_service.bal:39:33: mismatched input 'bind'. expecting ';'
error: restful_service/order_mgt_service.bal:39:47: mismatched input '{'. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:41:18: mismatched input '{'. expecting ';'
error: restful_service/order_mgt_service.bal:41:24: mismatched input ':'. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:43:10: mismatched input ':'. expecting ';'
error: restful_service/order_mgt_service.bal:43:26: extraneous input '{'
error: restful_service/order_mgt_service.bal:44:16: mismatched input ':'. expecting ';'
error: restful_service/order_mgt_service.bal:45:13: mismatched input ':'. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:47:14: mismatched input '('. expecting ';'
error: restful_service/order_mgt_service.bal:47:30: extraneous input ','
error: restful_service/order_mgt_service.bal:47:36: mismatched input ':'. expecting ';'
error: restful_service/order_mgt_service.bal:47:48: mismatched input ','. expecting ';'
error: restful_service/order_mgt_service.bal:47:64: mismatched input ')'. expecting ';'
error: restful_service/order_mgt_service.bal:51:21: mismatched input '=='. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:57:17: extraneous input '.'
error: restful_service/order_mgt_service.bal:57:32: mismatched input '('. expecting ';'
error: restful_service/order_mgt_service.bal:57:40: mismatched input ')'. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:60:20: mismatched input '->'. expecting {';', '.', '[', '?', '+', '-', '*', '/', '^', '%', '==', '!=', '>', '<', '>=', '<=', '&&', '||', '@'}
error: restful_service/order_mgt_service.bal:60:30: extraneous input '('
error: restful_service/order_mgt_service.bal:69:13: mismatched input '('. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:69:29: mismatched input ','. expecting ';'
error: restful_service/order_mgt_service.bal:69:47: mismatched input ')'. expecting ';'
error: restful_service/order_mgt_service.bal:70:24: extraneous input '?'
error: restful_service/order_mgt_service.bal:72:18: extraneous input '['
error: restful_service/order_mgt_service.bal:72:26: mismatched input ']'. expecting ';'
error: restful_service/order_mgt_service.bal:72:38: mismatched input ';'. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:77:17: extraneous input '.'
error: restful_service/order_mgt_service.bal:77:32: mismatched input '('. expecting ';'
error: restful_service/order_mgt_service.bal:77:40: mismatched input ')'. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:80:17: mismatched input '.'. expecting ';'
error: restful_service/order_mgt_service.bal:80:29: mismatched input '='. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:83:17: mismatched input '.'. expecting ';'
error: restful_service/order_mgt_service.bal:83:27: mismatched input '('. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:86:11: extraneous input '='
error: restful_service/order_mgt_service.bal:86:20: mismatched input '->'. expecting ';'
error: restful_service/order_mgt_service.bal:86:30: extraneous input '('
error: restful_service/order_mgt_service.bal:95:16: mismatched input '('. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:95:32: mismatched input ','. expecting ';'
error: restful_service/order_mgt_service.bal:95:50: mismatched input ','. expecting ';'
error: restful_service/order_mgt_service.bal:95:66: mismatched input ')'. expecting ';'
error: restful_service/order_mgt_service.bal:96:28: extraneous input '?'
error: restful_service/order_mgt_service.bal:102:27: mismatched input '!='. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:103:26: mismatched input '.'. expecting ';'
error: restful_service/order_mgt_service.bal:103:32: extraneous input '.'
error: restful_service/order_mgt_service.bal:104:26: extraneous input '.'
error: restful_service/order_mgt_service.bal:104:32: mismatched input '.'. expecting ';'
error: restful_service/order_mgt_service.bal:104:45: extraneous input '='
error: restful_service/order_mgt_service.bal:104:59: mismatched input '.'. expecting ';'
error: restful_service/order_mgt_service.bal:104:65: extraneous input '.'
error: restful_service/order_mgt_service.bal:105:22: extraneous input '['
error: restful_service/order_mgt_service.bal:105:30: mismatched input ']'. expecting ';'
error: restful_service/order_mgt_service.bal:105:47: mismatched input ';'. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:112:17: extraneous input '.'
error: restful_service/order_mgt_service.bal:112:32: mismatched input '('. expecting ';'
error: restful_service/order_mgt_service.bal:112:46: mismatched input ')'. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:114:20: mismatched input '->'. expecting {';', '.', '[', '?', '+', '-', '*', '/', '^', '%', '==', '!=', '>', '<', '>=', '<=', '&&', '||', '@'}
error: restful_service/order_mgt_service.bal:114:30: extraneous input '('
error: restful_service/order_mgt_service.bal:123:16: mismatched input '('. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:123:32: mismatched input ','. expecting ';'
error: restful_service/order_mgt_service.bal:123:50: mismatched input ','. expecting ';'
error: restful_service/order_mgt_service.bal:123:66: mismatched input ')'. expecting ';'
error: restful_service/order_mgt_service.bal:126:11: extraneous input '='
error: restful_service/order_mgt_service.bal:126:22: mismatched input '.'. expecting ';'
error: restful_service/order_mgt_service.bal:126:29: extraneous input '('
error: restful_service/order_mgt_service.bal:130:17: extraneous input '.'
error: restful_service/order_mgt_service.bal:130:32: mismatched input '('. expecting ';'
error: restful_service/order_mgt_service.bal:130:40: mismatched input ')'. expecting {'[', Identifier}
error: restful_service/order_mgt_service.bal:133:20: mismatched input '->'. expecting {';', '.', '[', '?', '+', '-', '*', '/', '^', '%', '==', '!=', '>', '<', '>=', '<=', '&&', '||', '@'}
error: restful_service/order_mgt_service.bal:133:30: extraneous input '('
ballerina: error writing program file 'restful_service.balx'
Dushans-MacBook-Pro-3:src dushan$

**Comment by pranavan15** [comment]
Hi Dushan,

This guide is written in Ballerina version 0.970_alpha1.  Since you are trying in an older version you are getting these errors.  

Further, all these guides are being migrated to upper versions vigorously. We will add a version tag once we stick to a stable version. 

Regards,
Pranavan

**Comment by pranavan15** [comment]
Hi Dushan,

This guide is written in Ballerina version 0.970_alpha1. Since you are trying in an older version you are getting these errors.

Further, all these guides are being migrated to upper versions vigorously. We will add a version tag once we stick to a stable version.

**Comment by pranavan15** [comment]
Hi Dushan,

This guide is written in Ballerina version 0.970_alpha1. Since you are trying in an older version, you are getting these errors.

Further, all these guides are being migrated to upper versions actively. We will add a version tag once we stick to a stable version.

**Comment by praneesha** [comment]
Closing as per the above comment.
