### ISSUE TITLE
Url Convention /orders or /order

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [ballerina-guides/restful-service#36]
**Description:**
Better to use resources as plural nouns in urls as it is a popular convention.
In the sample service comments urls are shown as /orders but actual urls are in singular form /order.
Either code or comments should be refactored.

**Suggested Labels:**
minor, convention, refactor

**Suggested Assignees:**
ShanikaEdiriweera. (I can PR if needed)

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamil321** [comment]
@ShanikaEdiriweera We appreciate your prompt feedback. Please go ahead and send a PR. I believe it is better to change the URL in comments as /order. The sample scenario is designed to address a single order.

**Comment by praneesha** [comment]
This has been fixed via [1].

[1] https://github.com/ballerina-guides/restful-service/pull/39/files
